/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package compilador_ada95;

import java.awt.Desktop;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author David
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        erroresLexicos = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaErroresLexicos = new javax.swing.JTextArea();
        erroresSintacticos = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        textAreaErroresSintacticos = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        ta_errores = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        textAreaErroresLexicos.setEditable(false);
        textAreaErroresLexicos.setColumns(20);
        textAreaErroresLexicos.setRows(5);
        jScrollPane2.setViewportView(textAreaErroresLexicos);

        javax.swing.GroupLayout erroresLexicosLayout = new javax.swing.GroupLayout(erroresLexicos.getContentPane());
        erroresLexicos.getContentPane().setLayout(erroresLexicosLayout);
        erroresLexicosLayout.setHorizontalGroup(
            erroresLexicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(erroresLexicosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 697, Short.MAX_VALUE)
                .addContainerGap())
        );
        erroresLexicosLayout.setVerticalGroup(
            erroresLexicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(erroresLexicosLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                .addContainerGap())
        );

        textAreaErroresSintacticos.setEditable(false);
        textAreaErroresSintacticos.setColumns(20);
        textAreaErroresSintacticos.setRows(5);
        jScrollPane3.setViewportView(textAreaErroresSintacticos);

        javax.swing.GroupLayout erroresSintacticosLayout = new javax.swing.GroupLayout(erroresSintacticos.getContentPane());
        erroresSintacticos.getContentPane().setLayout(erroresSintacticosLayout);
        erroresSintacticosLayout.setHorizontalGroup(
            erroresSintacticosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(erroresSintacticosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 697, Short.MAX_VALUE)
                .addContainerGap())
        );
        erroresSintacticosLayout.setVerticalGroup(
            erroresSintacticosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(erroresSintacticosLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Compilador ADA95");

        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        jButton1.setText("Compilar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        ta_errores.setColumns(20);
        ta_errores.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        ta_errores.setRows(5);
        jScrollPane4.setViewportView(ta_errores);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 184, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );

        jMenu1.setText("Archivo");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem3.setText("Cargar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem1.setText("Guardar");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            guardarDatos();
        } catch (IOException ex) {
            ex.printStackTrace();
        }
        if(archivo!=null){
            try{
                Yylex lexer;
                parser p;
                lexer  = new Yylex(new FileReader(archivo)); 
                p = new parser(lexer);
                p.parse();
                ta_errores.setText("");
                if (p.errores.isEmpty() && lexer.erroresLexicos.isEmpty()){
                    JOptionPane.showMessageDialog(this, "Código compilado sin ningún problema ","Información", JOptionPane.INFORMATION_MESSAGE);
                    String formato = "edge [color=red];" + hacerDFS(p.raiz);
                    p.raiz.exportarArbol(formato, "AST"); 
                    parser2 p2 = new parser2(new Yylex(new FileReader(archivo)));
                    p2.setArbol(p.raiz);
                    p2.setErrores(p.errores);
                    p2.parse();
                    JOptionPane.showMessageDialog(this, "No hay problema en el segundo parser");

                }
                else if (!lexer.erroresLexicos.isEmpty()){
                    JOptionPane.showMessageDialog(this, "Se han encontrado errores léxicos  ","Información", JOptionPane.INFORMATION_MESSAGE);
                    ta_errores.setText("ERRORES LEXICOS: \n");
                    for (int i = 0; i < lexer.erroresLexicos.size(); i++) {
                        ta_errores.setText(ta_errores.getText()+lexer.erroresLexicos.get(i)+"\n");
                    }

                }
                else if (!p.errores.isEmpty()){
                    JOptionPane.showMessageDialog(this, "Se han encontrado errores sintácticos ","Información", JOptionPane.INFORMATION_MESSAGE);
                    ta_errores.setText("ERRORES SINTACTICOS: \n");
                    for (int i = 0; i < p.errores.size(); i++) {
                        ta_errores.setText(ta_errores.getText()+p.errores.get(i)+"\n");
                    }
 
                }
                  
            }catch(Exception e){
                    e.printStackTrace();
            }
        }
        
        else{
            JOptionPane.showMessageDialog(this, "Todavía no ha escrito codigo","Información", JOptionPane.INFORMATION_MESSAGE);
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        File archivo = new File("C:\\Users\\mejia\\Desktop\\C\\Pruebas\\Prueba2.adb") ;
        textArea.setText("procedure Hola () is\n" +
                            "begin	\n" +
                            "	if(numero>67) then\n" +
                            "		put(\"Dentro del if\");\n" +
                            "		numero:=numero+1;\n" +
                            "		holis:=hola+2;\n" +
                            "	else\n" +
                            "		put(\"Dentro del else\");	\n" +
                            "		num:=n+3;\n" +
                            "	end if;\n" +
                            "\n" +
                            "	put(\"Fuera de todo\");\n" +
                            "	nada:=numero+1+3+4;\n" +
                            "\n" +
                            "end CUENTA; ");
       /* JFileChooser file=new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("ADA 95", "adb");
        file.addChoosableFileFilter(filtro);
        file.setAcceptAllFileFilterUsed(false);
        file.showOpenDialog(this);
        archivo=file.getSelectedFile();
        String aux="";
        String texto = "";
        if(archivo!=null)
            {     
                FileReader archivos = null;
                try {
                    archivos = new FileReader(archivo);
                } 
                catch (FileNotFoundException ex) {
                    Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                BufferedReader lee=new BufferedReader(archivos);
                try {
                    while((aux=lee.readLine())!=null)
                    {
                        texto+= aux+ "\n";
                    }
                    textArea.setText(texto);
                } 
                catch (IOException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                try {
                    lee.close();
                } 
                catch (IOException ex) {
                    Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        else{
            //JOptionPane.showMessageDialog(null,""+"\nNo se ha encontrado el archivo", "Advertencia",JOptionPane.WARNING_MESSAGE);
        }*/
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        try {
            guardarDatos();
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jMenu1ActionPerformed

    public void guardarDatos() throws IOException{
        FileWriter  save=new FileWriter(archivo);
        save.write(textArea.getText());
        save.close();
    }
    
    
    public String hacerDFS(Nodo node) {
        ArrayList<String> recorrido = new ArrayList<>();
        DFS(node, recorrido);
        DFSAristas(node, node.getIdNodo(), recorrido);
        String formato = "";
        for (int i = 0; i < recorrido.size(); i++) {
            formato += recorrido.get(i);
        }
        return formato;
    }

    public void DFS(Nodo node, ArrayList<String> recorrido) {
        if (!node.getEtiqueta().equals("VACIO")) {
            //System.out.println(node.toString());
            recorrido.add(node.toString());
        }
        for (int i = 0; i < node.getHijos().size(); i++) {
            DFS(node.getHijos().get(i), recorrido);
        }
    }

    public void DFSAristas(Nodo node, int padre, ArrayList<String> recorrido) {
        if (node.getIdNodo() != padre) {
            if (!node.getEtiqueta().equals("VACIO")) {
                recorrido.add(padre + "->" + node.getIdNodo() + ";");
            }
        }
        for (int i = 0; i < node.getHijos().size(); i++) {
            DFSAristas(node.getHijos().get(i), node.getIdNodo(), recorrido);
        }
    }
    
           
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog erroresLexicos;
    private javax.swing.JDialog erroresSintacticos;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea ta_errores;
    private javax.swing.JTextArea textArea;
    private javax.swing.JTextArea textAreaErroresLexicos;
    private javax.swing.JTextArea textAreaErroresSintacticos;
    // End of variables declaration//GEN-END:variables
File archivo = new File("C:\\Users\\mejia\\Desktop\\C\\Pruebas\\Prueba2.adb") ;


        


            

}

