
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package compilador_ada95;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TK_INOUT = 28;
  public static final int TK_OUT = 27;
  public static final int TK_ENDLOOP = 10;
  public static final int TK_FOR = 43;
  public static final int TK_IS = 20;
  public static final int TK_IGUAL = 2;
  public static final int TK_AND = 41;
  public static final int TK_OR = 42;
  public static final int TK_IN = 26;
  public static final int TK_BEGIN = 21;
  public static final int TK_OPREL = 15;
  public static final int TK_GET = 24;
  public static final int TK_ELSEIF = 8;
  public static final int TK_PARENTESISI = 34;
  public static final int TK_IF = 6;
  public static final int TK_ID = 14;
  public static final int TK_PARENTESISD = 35;
  public static final int TK_BOOLEAN = 4;
  public static final int TK_LOOP = 9;
  public static final int TK_EXIT = 29;
  public static final int TK_OPADICION = 12;
  public static final int TK_RETURN = 32;
  public static final int TK_TRUE = 38;
  public static final int TK_COMA = 37;
  public static final int TK_DIGITO = 16;
  public static final int TK_COLON = 40;
  public static final int EOF = 0;
  public static final int TK_ENDIF = 18;
  public static final int TK_PUNTO = 44;
  public static final int error = 1;
  public static final int TK_WHILE = 11;
  public static final int TK_FLOAT = 5;
  public static final int TK_DIGITOFLOAT = 25;
  public static final int TK_ELSE = 7;
  public static final int TK_MULTI = 13;
  public static final int TK_END = 22;
  public static final int TK_FALSE = 39;
  public static final int TK_THEN = 17;
  public static final int TK_PROCEDURE = 19;
  public static final int TK_STRING = 33;
  public static final int TK_FUNCTION = 31;
  public static final int TK_PUNTOCOMA = 36;
  public static final int TK_PUT = 23;
  public static final int TK_WHEN = 30;
  public static final int TK_INTEGER = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TK_IGUAL",
  "TK_INTEGER",
  "TK_BOOLEAN",
  "TK_FLOAT",
  "TK_IF",
  "TK_ELSE",
  "TK_ELSEIF",
  "TK_LOOP",
  "TK_ENDLOOP",
  "TK_WHILE",
  "TK_OPADICION",
  "TK_MULTI",
  "TK_ID",
  "TK_OPREL",
  "TK_DIGITO",
  "TK_THEN",
  "TK_ENDIF",
  "TK_PROCEDURE",
  "TK_IS",
  "TK_BEGIN",
  "TK_END",
  "TK_PUT",
  "TK_GET",
  "TK_DIGITOFLOAT",
  "TK_IN",
  "TK_OUT",
  "TK_INOUT",
  "TK_EXIT",
  "TK_WHEN",
  "TK_FUNCTION",
  "TK_RETURN",
  "TK_STRING",
  "TK_PARENTESISI",
  "TK_PARENTESISD",
  "TK_PUNTOCOMA",
  "TK_COMA",
  "TK_TRUE",
  "TK_FALSE",
  "TK_COLON",
  "TK_AND",
  "TK_OR",
  "TK_FOR",
  "TK_PUNTO"
  };
}

