
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package compilador_ada95;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TK_ENDLOOP = 19;
  public static final int TK_OPREL = 7;
  public static final int TK_PARENTESISI = 4;
  public static final int TK_PROCEDURE = 23;
  public static final int TK_OPADICION = 21;
  public static final int TK_PARENTESISD = 5;
  public static final int TK_IGUAL = 13;
  public static final int TK_ELSE = 3;
  public static final int TK_ENDIF = 11;
  public static final int TK_LETRA = 9;
  public static final int TK_WHILE = 20;
  public static final int TK_BOOLEAN = 15;
  public static final int TK_THEN = 10;
  public static final int TK_MULTI = 22;
  public static final int TK_PUNTOCOMA = 12;
  public static final int TK_LOOP = 18;
  public static final int TK_COLON = 29;
  public static final int EOF = 0;
  public static final int TK_TRUE = 27;
  public static final int TK_IS = 24;
  public static final int TK_AND = 30;
  public static final int TK_BEGIN = 25;
  public static final int TK_OR = 31;
  public static final int TK_INTEGER = 14;
  public static final int error = 1;
  public static final int TK_FLOAT = 16;
  public static final int TK_COMA = 17;
  public static final int TK_DIGITO = 8;
  public static final int TK_END = 26;
  public static final int TK_FALSE = 28;
  public static final int TK_IF = 2;
  public static final int TK_ID = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TK_IF",
  "TK_ELSE",
  "TK_PARENTESISI",
  "TK_PARENTESISD",
  "TK_ID",
  "TK_OPREL",
  "TK_DIGITO",
  "TK_LETRA",
  "TK_THEN",
  "TK_ENDIF",
  "TK_PUNTOCOMA",
  "TK_IGUAL",
  "TK_INTEGER",
  "TK_BOOLEAN",
  "TK_FLOAT",
  "TK_COMA",
  "TK_LOOP",
  "TK_ENDLOOP",
  "TK_WHILE",
  "TK_OPADICION",
  "TK_MULTI",
  "TK_PROCEDURE",
  "TK_IS",
  "TK_BEGIN",
  "TK_END",
  "TK_TRUE",
  "TK_FALSE",
  "TK_COLON",
  "TK_AND",
  "TK_OR"
  };
}

