// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: lexer.txt

package compilador_ada95;

import java_cup.runtime.Symbol;
import javax.swing.JOptionPane;
import java.util.ArrayList;


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class Yylex implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int COMENTARIOS = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1, 1
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\12\0\1\1\2\2\1\3\22\0\1\4\1\0\1\5"+
    "\3\0\1\6\1\0\1\7\1\10\1\11\1\12\1\13"+
    "\1\14\1\15\1\11\12\16\1\17\1\20\1\21\1\22"+
    "\1\21\2\0\1\23\1\24\2\25\1\26\1\27\1\30"+
    "\1\25\1\31\2\25\1\32\1\25\1\33\1\34\2\25"+
    "\1\35\1\25\1\36\6\25\4\0\1\37\1\0\1\40"+
    "\1\41\1\42\1\43\1\44\1\45\1\46\1\47\1\50"+
    "\2\25\1\51\1\25\1\52\1\53\1\54\1\25\1\55"+
    "\1\56\1\57\1\60\1\25\1\61\1\62\2\25\1\0"+
    "\1\63\10\0\1\2\u01a2\0\2\2\326\0\u0100\2";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\2\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\10\1\1\1\12\1\13\1\14\2\15"+
    "\4\16\1\1\13\16\1\17\1\20\2\21\1\0\1\22"+
    "\1\23\1\24\1\0\13\25\1\26\1\27\1\30\15\25"+
    "\1\31\3\25\1\32\2\25\1\33\1\25\1\34\11\25"+
    "\1\35\1\0\1\36\3\25\1\37\2\25\1\40\1\41"+
    "\1\42\2\25\1\43\1\25\1\44\1\25\2\0\1\45"+
    "\1\25\1\46\2\25\1\47\2\25\1\50\1\51\1\0"+
    "\2\25\1\52\1\53\1\54\1\0\2\25\1\55\1\56"+
    "\1\25\1\57";

  private static int [] zzUnpackAction() {
    int [] result = new int[133];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\64\0\150\0\234\0\150\0\150\0\150\0\150"+
    "\0\150\0\150\0\320\0\150\0\u0104\0\u0138\0\320\0\u016c"+
    "\0\150\0\u01a0\0\150\0\u01d4\0\u0208\0\u023c\0\u0270\0\u02a4"+
    "\0\u02d8\0\u030c\0\u0340\0\u0374\0\u03a8\0\u03dc\0\u0410\0\u0444"+
    "\0\u0478\0\u04ac\0\u04e0\0\150\0\150\0\u0514\0\150\0\u0138"+
    "\0\150\0\u0138\0\150\0\u0548\0\u01d4\0\u057c\0\u05b0\0\u05e4"+
    "\0\u0618\0\u064c\0\u0680\0\u06b4\0\u06e8\0\u071c\0\u0750\0\u01d4"+
    "\0\u0784\0\u01d4\0\u07b8\0\u07ec\0\u0820\0\u0854\0\u0888\0\u08bc"+
    "\0\u08f0\0\u0924\0\u0958\0\u098c\0\u09c0\0\u09f4\0\u0a28\0\u0a5c"+
    "\0\u0a90\0\u0ac4\0\u0af8\0\u01d4\0\u0b2c\0\u0b60\0\u01d4\0\u0b94"+
    "\0\u01d4\0\u0bc8\0\u0bfc\0\u0c30\0\u0c64\0\u0c98\0\u0ccc\0\u0d00"+
    "\0\u0d34\0\u0d68\0\u0d9c\0\u0dd0\0\u01d4\0\u0e04\0\u0e38\0\u0e6c"+
    "\0\u01d4\0\u0ea0\0\u0ed4\0\u01d4\0\u01d4\0\u01d4\0\u0f08\0\u0f3c"+
    "\0\u01d4\0\u0f70\0\u01d4\0\u0fa4\0\u0fd8\0\u100c\0\u01d4\0\u1040"+
    "\0\u01d4\0\u1074\0\u10a8\0\u01d4\0\u10dc\0\u1110\0\u01d4\0\150"+
    "\0\u1144\0\u1178\0\u11ac\0\u01d4\0\u01d4\0\u01d4\0\u11e0\0\u1214"+
    "\0\u1248\0\150\0\u01d4\0\u127c\0\u01d4";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[133];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\0\2\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\24\1\25\2\24\1\26\1\24\1\27"+
    "\5\24\1\30\1\24\1\31\2\24\1\32\1\33\1\34"+
    "\1\24\1\35\1\36\1\24\1\37\1\40\1\41\1\24"+
    "\1\42\1\24\1\43\1\24\1\44\1\45\1\46\1\0"+
    "\1\47\60\45\67\0\1\5\75\0\1\50\1\17\61\0"+
    "\1\51\1\50\1\17\63\0\1\52\67\0\1\53\63\0"+
    "\1\23\53\0\1\54\1\0\1\54\1\0\1\55\4\0"+
    "\40\55\13\0\1\54\1\0\1\54\1\0\1\55\4\0"+
    "\11\55\1\56\26\55\13\0\1\54\1\0\1\54\1\0"+
    "\1\55\4\0\7\55\1\57\30\55\13\0\1\54\1\0"+
    "\1\54\1\0\1\55\4\0\10\55\1\60\27\55\24\0"+
    "\14\55\1\0\23\55\13\0\1\54\1\0\1\54\1\0"+
    "\1\55\4\0\21\55\1\61\16\55\13\0\1\54\1\0"+
    "\1\54\1\0\1\55\4\0\26\55\1\62\1\63\7\55"+
    "\1\64\13\0\1\54\1\0\1\54\1\0\1\55\4\0"+
    "\15\55\1\65\17\55\1\66\2\55\13\0\1\54\1\0"+
    "\1\54\1\0\1\55\4\0\21\55\1\67\16\55\13\0"+
    "\1\54\1\0\1\54\1\0\1\55\4\0\22\55\1\70"+
    "\4\55\1\71\3\55\1\72\4\55\13\0\1\54\1\0"+
    "\1\54\1\0\1\55\4\0\30\55\1\73\7\55\13\0"+
    "\1\54\1\0\1\54\1\0\1\55\4\0\35\55\1\74"+
    "\2\55\13\0\1\54\1\0\1\54\1\0\1\55\4\0"+
    "\32\55\1\75\2\55\1\76\2\55\13\0\1\54\1\0"+
    "\1\54\1\0\1\55\4\0\21\55\1\77\16\55\13\0"+
    "\1\54\1\0\1\54\1\0\1\55\4\0\24\55\1\100"+
    "\5\55\1\101\5\55\13\0\1\54\1\0\1\54\1\0"+
    "\1\55\4\0\24\55\1\102\13\55\4\0\1\47\76\0"+
    "\1\55\57\0\1\54\1\0\1\54\1\0\1\55\4\0"+
    "\11\55\1\103\26\55\13\0\1\54\1\0\1\54\1\0"+
    "\1\55\4\0\11\55\1\104\26\55\13\0\1\54\1\0"+
    "\1\54\1\0\1\55\4\0\13\55\1\105\24\55\13\0"+
    "\1\54\1\0\1\54\1\0\1\55\4\0\23\55\1\106"+
    "\14\55\13\0\1\54\1\0\1\54\1\0\1\55\4\0"+
    "\33\55\1\107\4\55\13\0\1\54\1\0\1\54\1\0"+
    "\1\55\4\0\20\55\1\110\17\55\13\0\1\54\1\0"+
    "\1\54\1\0\1\55\4\0\25\55\1\111\12\55\13\0"+
    "\1\54\1\0\1\54\1\0\1\55\4\0\26\55\1\112"+
    "\11\55\13\0\1\54\1\0\1\54\1\0\1\55\4\0"+
    "\27\55\1\113\10\55\13\0\1\54\1\0\1\54\1\0"+
    "\1\55\4\0\34\55\1\114\3\55\13\0\1\54\1\0"+
    "\1\54\1\0\1\55\4\0\30\55\1\115\7\55\13\0"+
    "\1\54\1\0\1\54\1\0\1\55\4\0\30\55\1\116"+
    "\7\55\13\0\1\54\1\0\1\54\1\0\1\55\4\0"+
    "\34\55\1\117\3\55\13\0\1\54\1\0\1\54\1\0"+
    "\1\55\4\0\30\55\1\120\7\55\13\0\1\54\1\0"+
    "\1\54\1\0\1\55\4\0\34\55\1\121\3\55\13\0"+
    "\1\54\1\0\1\54\1\0\1\55\4\0\34\55\1\122"+
    "\3\55\13\0\1\54\1\0\1\54\1\0\1\55\4\0"+
    "\21\55\1\123\16\55\13\0\1\54\1\0\1\54\1\0"+
    "\1\55\4\0\35\55\1\124\2\55\13\0\1\54\1\0"+
    "\1\54\1\0\1\55\4\0\21\55\1\125\3\55\1\126"+
    "\12\55\13\0\1\54\1\0\1\54\1\0\1\55\4\0"+
    "\7\55\1\127\30\55\13\0\1\54\1\0\1\54\1\0"+
    "\1\55\4\0\1\130\37\55\13\0\1\54\1\0\1\54"+
    "\1\0\1\55\4\0\3\55\1\131\34\55\13\0\1\54"+
    "\1\0\1\54\1\0\1\55\4\0\25\55\1\132\12\55"+
    "\13\0\1\54\1\0\1\54\1\0\1\55\4\0\21\55"+
    "\1\133\16\55\5\0\1\134\5\0\1\54\1\0\1\54"+
    "\1\0\1\55\4\0\40\55\13\0\1\54\1\0\1\54"+
    "\1\0\1\55\4\0\34\55\1\135\3\55\13\0\1\54"+
    "\1\0\1\54\1\0\1\55\4\0\33\55\1\136\4\55"+
    "\13\0\1\54\1\0\1\54\1\0\1\55\4\0\17\55"+
    "\1\137\20\55\13\0\1\54\1\0\1\54\1\0\1\55"+
    "\4\0\35\55\1\140\2\55\13\0\1\54\1\0\1\54"+
    "\1\0\1\55\4\0\31\55\1\141\6\55\13\0\1\54"+
    "\1\0\1\54\1\0\1\55\4\0\17\55\1\142\20\55"+
    "\13\0\1\54\1\0\1\54\1\0\1\55\4\0\35\55"+
    "\1\143\2\55\13\0\1\54\1\0\1\54\1\0\1\55"+
    "\4\0\27\55\1\144\10\55\13\0\1\54\1\0\1\54"+
    "\1\0\1\55\4\0\21\55\1\145\16\55\13\0\1\54"+
    "\1\0\1\54\1\0\1\55\4\0\27\55\1\146\10\55"+
    "\13\0\1\54\1\0\1\54\1\0\1\55\4\0\26\55"+
    "\1\147\11\55\13\0\1\54\1\0\1\54\1\0\1\55"+
    "\4\0\3\55\1\150\34\55\13\0\1\54\1\0\1\54"+
    "\1\0\1\55\4\0\13\55\1\151\24\55\13\0\1\54"+
    "\1\0\1\54\1\0\1\55\4\0\5\55\1\152\32\55"+
    "\13\0\1\54\1\0\1\54\1\0\1\55\4\0\27\55"+
    "\1\153\10\55\13\0\1\54\1\0\1\54\1\0\1\55"+
    "\4\0\25\55\1\154\12\55\5\0\1\134\43\0\1\155"+
    "\1\156\24\0\1\54\1\0\1\54\1\0\1\55\4\0"+
    "\21\55\1\157\16\55\13\0\1\54\1\0\1\54\1\0"+
    "\1\55\4\0\34\55\1\160\3\55\13\0\1\54\1\0"+
    "\1\54\1\0\1\55\4\0\34\55\1\161\3\55\13\0"+
    "\1\54\1\0\1\54\1\0\1\55\4\0\21\55\1\162"+
    "\16\55\13\0\1\54\1\0\1\54\1\0\1\55\4\0"+
    "\32\55\1\163\5\55\13\0\1\54\1\0\1\54\1\0"+
    "\1\55\4\0\21\55\1\164\16\55\13\0\1\54\1\0"+
    "\1\54\1\0\1\55\4\0\1\165\37\55\13\0\1\54"+
    "\1\0\1\54\1\0\1\55\4\0\3\55\1\166\34\55"+
    "\13\0\1\54\1\0\1\54\1\0\1\55\4\0\22\55"+
    "\1\167\15\55\46\0\1\170\71\0\1\171\22\0\1\54"+
    "\1\0\1\54\1\0\1\55\4\0\25\55\1\172\12\55"+
    "\13\0\1\54\1\0\1\54\1\0\1\55\4\0\20\55"+
    "\1\173\17\55\13\0\1\54\1\0\1\54\1\0\1\55"+
    "\4\0\27\55\1\174\10\55\13\0\1\54\1\0\1\54"+
    "\1\0\1\55\4\0\10\55\1\175\27\55\13\0\1\54"+
    "\1\0\1\54\1\0\1\55\4\0\12\55\1\176\25\55"+
    "\54\0\1\177\22\0\1\54\1\0\1\54\1\0\1\55"+
    "\4\0\30\55\1\200\7\55\13\0\1\54\1\0\1\54"+
    "\1\0\1\55\4\0\35\55\1\201\2\55\55\0\1\202"+
    "\21\0\1\54\1\0\1\54\1\0\1\55\4\0\27\55"+
    "\1\203\10\55\13\0\1\54\1\0\1\54\1\0\1\55"+
    "\4\0\32\55\1\204\5\55\13\0\1\54\1\0\1\54"+
    "\1\0\1\55\4\0\21\55\1\205\16\55\1\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4784];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\1\1\6\11\1\1\1\11\4\1\1\11"+
    "\1\1\1\11\20\1\2\11\1\1\1\11\1\0\1\11"+
    "\1\1\1\11\1\0\57\1\1\0\20\1\2\0\11\1"+
    "\1\11\1\0\5\1\1\0\2\1\1\11\3\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[133];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    String comentario="";
    ArrayList erroresLexicos = new ArrayList();
    


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Yylex(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { erroresLexicos.add("Error lexico en linea "+yyline+" y columna "+yycolumn+" y en el texto: "+yytext());
            }
            // fall through
          case 48: break;
          case 2:
            { 
            }
            // fall through
          case 49: break;
          case 3:
            { System.out.println("Comilla -  "+yytext());return new Symbol (sym.TK_COMILLA, yyline + 1, yycolumn +1 , yytext() ) ;
            }
            // fall through
          case 50: break;
          case 4:
            { return new Symbol (sym.TK_AND, yyline + 1, yycolumn +1 , yytext() ) ;
            }
            // fall through
          case 51: break;
          case 5:
            { return new Symbol (sym.TK_PARENTESISI, yyline + 1, yycolumn +1 , yytext() ) ;
            }
            // fall through
          case 52: break;
          case 6:
            { return new Symbol (sym.TK_PARENTESISD, yyline + 1, yycolumn +1 , yytext() ) ;
            }
            // fall through
          case 53: break;
          case 7:
            { return new Symbol (sym.TK_MULTI, yyline + 1, yycolumn +1 , yytext() ) ;
            }
            // fall through
          case 54: break;
          case 8:
            { return new Symbol (sym.TK_OPADICION, yyline + 1, yycolumn +1 , yytext() ) ;
            }
            // fall through
          case 55: break;
          case 9:
            { return new Symbol (sym.TK_COMA, yyline + 1, yycolumn +1 , yytext() ) ;
            }
            // fall through
          case 56: break;
          case 10:
            { System.out.println("Encontro un digito "+yytext());return new Symbol (sym.TK_DIGITO, yyline + 1, yycolumn +1 , yytext() ) ;
            }
            // fall through
          case 57: break;
          case 11:
            { return new Symbol (sym.TK_COLON, yyline + 1, yycolumn +1 , yytext() ) ;
            }
            // fall through
          case 58: break;
          case 12:
            { return new Symbol (sym.TK_PUNTOCOMA, yyline + 1, yycolumn +1 , yytext() ) ;
            }
            // fall through
          case 59: break;
          case 13:
            { return new Symbol (sym.TK_OPREL, yyline + 1, yycolumn +1 , yytext() ) ;
            }
            // fall through
          case 60: break;
          case 14:
            { return new Symbol (sym.TK_LETRA, yyline + 1, yycolumn +1 , yytext() ) ;
            }
            // fall through
          case 61: break;
          case 15:
            { return new Symbol (sym.TK_OR, yyline + 1, yycolumn +1 , yytext() ) ;
            }
            // fall through
          case 62: break;
          case 16:
            { comentario = comentario+yytext();
            }
            // fall through
          case 63: break;
          case 17:
            { System.out.println("Este es un comentario: "+comentario); comentario =" ";yybegin(YYINITIAL);
            }
            // fall through
          case 64: break;
          case 18:
            { yybegin(COMENTARIOS);
            }
            // fall through
          case 65: break;
          case 19:
            { System.out.println("Encontro un digito float "+yytext());return new Symbol (sym.TK_DIGITOFLOAT, yyline + 1, yycolumn +1 , yytext() ) ;
            }
            // fall through
          case 66: break;
          case 20:
            { System.out.println("Encontro un igual");return new Symbol (sym.TK_IGUAL, yyline + 1, yycolumn +1 , yytext() ) ;
            }
            // fall through
          case 67: break;
          case 21:
            { System.out.println("Encontro un id - "+yytext());return new Symbol (sym.TK_ID, yyline + 1, yycolumn +1 , yytext() ) ;
            }
            // fall through
          case 68: break;
          case 22:
            { System.out.println("Encontro un if - "+yytext());return new Symbol (sym.TK_IF, yyline + 1, yycolumn +1 , yytext() ) ;
            }
            // fall through
          case 69: break;
          case 23:
            { return new Symbol (sym.TK_IN, yyline + 1, yycolumn +1 , yytext() ) ;
            }
            // fall through
          case 70: break;
          case 24:
            { return new Symbol (sym.TK_IS, yyline + 1, yycolumn +1 , yytext() ) ;
            }
            // fall through
          case 71: break;
          case 25:
            { return new Symbol (sym.TK_END, yyline + 1, yycolumn +1 , yytext() ) ;
            }
            // fall through
          case 72: break;
          case 26:
            { return new Symbol (sym.TK_GET, yyline + 1, yycolumn +1 , yytext() ) ;
            }
            // fall through
          case 73: break;
          case 27:
            { return new Symbol (sym.TK_OUT, yyline + 1, yycolumn +1 , yytext() ) ;
            }
            // fall through
          case 74: break;
          case 28:
            { return new Symbol (sym.TK_PUT, yyline + 1, yycolumn +1 , yytext() ) ;
            }
            // fall through
          case 75: break;
          case 29:
            { return new Symbol (sym.TK_ELSE, yyline + 1, yycolumn +1 , yytext() ) ;
            }
            // fall through
          case 76: break;
          case 30:
            { return new Symbol (sym.TK_EXIT, yyline + 1, yycolumn +1 , yytext() ) ;
            }
            // fall through
          case 77: break;
          case 31:
            { return new Symbol (sym.TK_LOOP, yyline + 1, yycolumn +1 , yytext() ) ;
            }
            // fall through
          case 78: break;
          case 32:
            { System.out.println("Encontro un then - "+yytext());return new Symbol (sym.TK_THEN, yyline + 1, yycolumn +1 , yytext() ) ;
            }
            // fall through
          case 79: break;
          case 33:
            { return new Symbol (sym.TK_TRUE, yyline + 1, yycolumn +1 , yytext() ) ;
            }
            // fall through
          case 80: break;
          case 34:
            { return new Symbol (sym.TK_WHEN, yyline + 1, yycolumn +1 , yytext() ) ;
            }
            // fall through
          case 81: break;
          case 35:
            { System.out.println("Encontro un float");return new Symbol (sym.TK_FLOAT, yyline + 1, yycolumn +1 , yytext() ) ;
            }
            // fall through
          case 82: break;
          case 36:
            { return new Symbol (sym.TK_BEGIN, yyline + 1, yycolumn +1 , yytext() ) ;
            }
            // fall through
          case 83: break;
          case 37:
            { return new Symbol (sym.TK_FALSE, yyline + 1, yycolumn +1 , yytext() ) ;
            }
            // fall through
          case 84: break;
          case 38:
            { return new Symbol (sym.TK_INOUT, yyline + 1, yycolumn +1 , yytext() ) ;
            }
            // fall through
          case 85: break;
          case 39:
            { return new Symbol (sym.TK_WHILE, yyline + 1, yycolumn +1 , yytext() ) ;
            }
            // fall through
          case 86: break;
          case 40:
            { return new Symbol (sym.TK_ELSEIF, yyline + 1, yycolumn +1 , yytext() ) ;
            }
            // fall through
          case 87: break;
          case 41:
            { return new Symbol (sym.TK_ENDIF, yyline + 1, yycolumn +1 , yytext() ) ;
            }
            // fall through
          case 88: break;
          case 42:
            { return new Symbol (sym.TK_RETURN, yyline + 1, yycolumn +1 , yytext() ) ;
            }
            // fall through
          case 89: break;
          case 43:
            { System.out.println("Encontro un Boolean");return new Symbol (sym.TK_BOOLEAN, yyline + 1, yycolumn +1 , yytext() ) ;
            }
            // fall through
          case 90: break;
          case 44:
            { return new Symbol (sym.TK_INTEGER, yyline + 1, yycolumn +1 , yytext() ) ;
            }
            // fall through
          case 91: break;
          case 45:
            { return new Symbol (sym.TK_ENDLOOP, yyline + 1, yycolumn +1 , yytext() ) ;
            }
            // fall through
          case 92: break;
          case 46:
            { return new Symbol (sym.TK_FUNCTION, yyline + 1, yycolumn +1 , yytext() ) ;
            }
            // fall through
          case 93: break;
          case 47:
            { return new Symbol (sym.TK_PROCEDURE, yyline + 1, yycolumn +1 , yytext() ) ;
            }
            // fall through
          case 94: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
